Added spring cloud and dependency injection samples
Azure-Samples/azure-functions-samples-java pull request #40
Opened 2023-10-18 23:41 UTC by shreyas-gopalakrishna

Added spring cloud and dependency injection samples. Updated samples folder structure

Existing samples are moved inside the triggers-bindings folder 
Spring cloud and dependency injection samples are added in their respective folders 

Todo:
- add comments on samples for better readability 
- remove any unnecessary files

2023-10-19 21:46 UTC, shreyas-gopalakrishna commented on README.md
> +| [Distributed tracing](./triggers-bindings/src/main/java/com/functions/DistributedTracingFunction.java) | Distributed tracing example that adds entries to a MYSQL database via JDBC, adds custom metr
Yes, updated durable as well

2023-10-19 22:09 UTC, kamperiadis requested changes

2023-10-19 22:09 UTC, kamperiadis commented on distributed-tracing/host.json
> +    "version": "[3.*, 4.0.0)"
```suggestion
    "version": "[4.*, 5.0.0)"
```

2023-10-19 22:09 UTC, kamperiadis commented on durable-function/host.json
> +    "version": "[3.*, 4.0.0)"
```suggestion
    "version": "[4.*, 5.0.0)"
```

2023-10-19 22:09 UTC, kamperiadis commented on distributed-tracing/pom.xml
> +    </dependencies>
```suggestion
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.1.0</version>
        </dependency> 
       
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>12.4.1.jre11</version>
        </dependency>

        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
            <version>1.31.0</version>
        </dependency>

    </dependencies>
```

2023-10-20 14:12 UTC, kamperiadis approved these changes
LGTM! Thank you

2023-10-20 14:15 UTC, merged